# foundry.toml = configuration file + allows developers to specify various settings and configurations for their Foundry projects

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

ffi=true # allow foundry to run cmds directly on your machine